version: '3'
services:
  python_service:
    build:
      context: ./src/backend
      dockerfile: Dockerfile
    volumes:
      - ./:/home/
    ports:
      - "8880:8888"
    container_name: python_container
    depends_on:
      - model
      - db
    stdin_open: true
    tty: true
  db:
    image: postgres
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5434:5432"
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: "postgres_db"
      POSTGRES_USER: "user"
    container_name: db_container
  model:
    build:
      context: ./src/model
      dockerfile: Dockerfile
    volumes:
      - ./:/home/
    container_name: model_container
    depends_on:
      - db

volumes:
  pgdata:







